name: Bug Report
description: Found something you weren't expecting?  Report it here!
labels: ["Unconfirmed Bug"]
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report.
      NOTE: Please read the instructions below before filling the form.
- type: markdown
  attributes:
    value: |
      1. Please write in English, this is the language all maintainers can speak and write.
      2. Please take a moment to check that your issue doesn't already exist and not already reported.
      3. Please provide the information for each field as complete as possible.
- type: textarea
  id: phramer-ver
  attributes:
    label: Phramer Version
    description: The Phramer version (or commit reference) you are running. You can right-click on the tray icon > About > copy
    placeholder: e.g Phramer v14.1.3
  validations:
    required: true
- type: dropdown
  id: installation-type
  attributes:
    label: Installation Type
    description: How have you installed Phramer?
    multiple: true
    options:
      - Installer (.msi) from GitHub Releases
      - Portable ZIP from GitHub Releases
      - Updated in-place from an earlier version
      - Compiled from source
  validations:
    required: true
- type: input
  id: os-ver
  attributes:
    label: Windows version
    description: "The version of Windows you are using Phramer on (Settings > System > About):"
  validations:
    required: true
- type: textarea
  id: description
  attributes:
    label: Description
    description: |
      Please provide a description of your issue here. Please explain in details what the issue is. If you can, provide screenshots or screen recordings to demonstrate the issue.
  validations:
      required: true
- type: textarea
  id: steps-to-reproduce
  attributes:
    label: Steps to reproduce
    description: Please write the steps we should take to reproduce this buggy behaviour
    placeholder: |
      1. press Win+Shift+X to start a capture
      2. select a region on the primary monitor
      3. save to file
      4. ...
  validations:
      required: false
- type: textarea
  id: screenshots
  attributes:
    label: Screenshots or screen recordings
    description: If you think it would be beneficial for us to understand the issue, please provide a screenshot or screen recording.
- type: textarea
  id: systeminfo
  attributes:
    label: System Information
    description: |
      Please provide the detailed information about your computer including:
        1. Windows edition and version
        2. Your monitor configuration - the easiest way is a screenshot of Settings > System > Display, including the scaling percentage of each monitor
  validations:
      required: true
